### ISSUE TITLE
Property verification

### ISSUE THREAD

**Issue by jgheerardyn** [jgheerardyn/yields#40]
Two (known) issues

* in PropertyVerifications, we have this code:
```java
  public boolean allValid() {
        return results.values().stream().count() > 0 && results.values().stream().filter(PropertyVerification::isValid).count() == results.values().size();
    }
```
However, if we use Explorer to generate results without checking any property, the results are more naturally reported as valid.

* in PropertyVerifications, there is a map String -> PropertyVerification. The String refers to the Property that has been checked. It would be better if we have access to the property itself for multiple reasons.

**Comment by rombautt** [comment]
Implemented
