### ISSUE TITLE
Yields trend - KPI filtering

### ISSUE THREAD

**Issue by jgheerardyn** [jgheerardyn/yields#48]
Would it be possible to filter the KPI's that are shown in the average KPI trend? Ideally via using groups. In the KPI report though we need to show all KPI's / scores.

![image](https://cloud.githubusercontent.com/assets/6535557/5694992/ff0554aa-9986-11e4-8425-599cf0c6269b.png)

**Comment by jgheerardyn** [comment]
A bit more details:

tests defining scores can be assigned to various groups. Only the tests belonging to the group "official" are shown in the average trend. In the KPI report, results are mentioned together per group, ideally on different pages per group.

@Exporation(groups="official, vols")
sabrTest...

@Exploration(groups="vols")
hestonTest...

@Exploration(groups="curves")
curveTest...

averageKPI trend only contains score defined in sabrTest

in KPI report, we show three groups:
official
vols
curves

each group has a KPI report as currently; preferably one group per page/report

**Comment by rombautt** [comment]
Should be possible.

- record the groups in the persisted json files
- provide an entry to specify the name of the 'official' groups
- create tabs (or sth similar, to be checked as Jenkins is limited) with data per group

**Comment by jgheerardyn** [comment]
In addition, the reported scores have a more or less random order both in the table and in the report. Perhaps best would be to order by decreasing score.

**Comment by rombautt** [comment]
question: I'll add 2 fields to the Exploration annotation:

String group => used to show the tabs in KPI Report

boolean official => if true, the KPI will be part of the Average KPI trend

Supporting multiple groups would open possibilities for problems, as the same KPI would be reported in multiple tabs.

**Comment by rombautt** [comment]
Implemented, see screenshots attached.

**Comment by jgheerardyn** [comment]
Hi Tim,

thanks - looks good already. Could you just make sure that the KPI's in the table and graphs are reparted alphabetically? Same for the tabs.

Thanks
Jos

**Comment by rombautt** [comment]
This has been changed, see screenshots attached:

- tabs sorted alphabetically
- KPIs sorted alphabetically
- Test Names sorted alphabetically (in Average KPI Trend, they're sorted by descending score in the KPI Report)
- better formatting of tables: KPI names are left aligned
