### ISSUE TITLE
ExploreRunner improvement

### ISSUE THREAD

**Issue by jgheerardyn** [jgheerardyn/yields#49]
I cannot select a single @Explore test; all tests in the class are executed. Is this as expected?

**Comment by rombautt** [comment]
You can select the method name, right-click/Run; this will only run the individual method.

**Comment by jgheerardyn** [comment]
For some reason, when I run SabrImpliedDensityTest.testBerestycki (in Yields-Finance), IntelliJ claims it has run 1 test, but three json files are written (this test class contains three tests). See screenshot attached.

![image](https://cloud.githubusercontent.com/assets/6535557/5737381/57fe024a-9be0-11e4-994a-1832f9416ae3.png)

**Comment by rombautt** [comment]
You're right, the ExploreRunner was over-eagerly executing, before the JUnit filter was applied.

Persisting the scores is now done after the test completes, and only for the tests passing the JUnit filter.
