### ISSUE TITLE
KPI logic

### ISSUE THREAD

**Issue by jgheerardyn** [jgheerardyn/yields#61]
Currently, KPI's work on the total of generated objects. And scores work on a group of KPI's. There is however an additional intermediate step needed that maps the verification to a sort of quality measure. The KPI then takes the quality measures and turns it into a number.

This way, the quality measures can be computed on a single outcome. This means we can also persist these measures in the csv export and we could evaluate/benchmark a single outcome

**Comment by jgheerardyn** [comment]
Idea is to add a Stats object that contains the interesting statistics for visualization purposes.

**Comment by jgheerardyn** [comment]
Hi Tim,

I have added a descriptor to the Stats object as well - which should be included in the csv export as with the other stats.

I'll now make a realistic example in Yields-finance.

J

**Comment by rombautt** [comment]
Changed:

- now use code of PropertyVerificationResult iso label
- added descriptors to CSV

**Comment by rombautt** [comment]
FYI: I saw this test failed: 

Failed tests: 
  6_43 [z: 0.9999879018810226](org.apache.commons.math3.special.SpecialFunctionTest): Property EQ 0.000000 fails on functional  evaluated at z=9.999879E-1 with value -1.6902049537748098E-7.

Though not all the time.
