### ISSUE TITLE
timestamps

### ISSUE THREAD

**Issue by jgheerardyn** [jgheerardyn/yields#87]
Currently, a timestamp is appended to the json/csv filenames (e.g. Berestycki_option_02042015001328.json). However, since the folder structure already contains the date/time information, this timestamp at the end of the filename is not needed. As it also reduces the readability in the TestPad screens, this suffix should be removed.

**Comment by rombautt** [comment]
Could we keep it in the name of the file, as it make it unique.
Instead, I would just have testpad remove the suffix when displaying, agree?

**Comment by rombautt** [comment]
Changed in yields-private: tests are now displayed without the timestamp suffix in all screens.

**Comment by jgheerardyn** [comment]
ok - closing current issue
