### ISSUE TITLE
KPI report

### ISSUE THREAD

**Issue by jgheerardyn** [jgheerardyn/yields#92]
When a Jenkins build fails, the graphs are truncated at that point.

Build 14 (-3 in the graph) failed....

![image](https://cloud.githubusercontent.com/assets/6535557/8004256/795e058a-0b7e-11e5-92c9-ff76ff986184.png)

**Comment by rombautt** [comment]
This has been fixed, only successful builds are used in the graphs and tables.

Also: for the Yields KPI Reports the build numbers are now the real build numbers iso 0, -1, -2, ...

See screenshots attached.

**Comment by rombautt** [comment]
![yields_92_1](https://cloud.githubusercontent.com/assets/462553/8271859/1919db16-182d-11e5-9c33-37c8179fcb55.png)
![yields_92_2](https://cloud.githubusercontent.com/assets/462553/8271860/1942429a-182d-11e5-97a6-ffcb2950d0bb.png)
